version: "3.8"

services:
  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VUE_APP_API_URL: http://localhost:7000
      BASE_URL: http://localhost:8080
    ports:
      - "8080:8080"
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: teste_receitas_rg_sistemas
    ports:
      - "3306:3306"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DB_NAME: teste_receitas_rg_sistemas
      DB_USER: root
      DB_PASSWORD:
      DB_HOST: mysql
      DB_PORT: 3306
      FRONTEND_URL: http://localhost:8080
      JWT_SECRET: ?secretjwt
      PORT: 7000
    ports:
      - "7000:7000"
    depends_on:
      - mysql
    command:
      ["./wait-for-it.sh", "mysql:3306", "-t", "45", "--", "npm", "run", "dev"]
    restart: always
